### ISSUE TITLE
Nota 7 tareas

### ISSUE THREAD

**Issue by VicenteMerino** [PUCIIC2513/2020-2#1]
Hola, el enunciado dice:

![image](https://user-images.githubusercontent.com/47841749/90670011-8bc51000-e220-11ea-8e4d-1b1887689ad9.png)

Según los comentarios de compañeros, para optar al 7 en semestres anteriores, había que realizar algo adicional en la tarea que no estuviera en el enunciado. No se si esto es algo que se repetirá este semestre y eso se refiere con "Avance mayor del solicitado".

Gracias

**Comment by VicenteMerino** [comment]
Pd: creo que no está habilitado para que nosotros podamos poner etiquetas.

**Comment by B-Dominguez** [comment]
Hola Vicente,

Para la tarea 1, el 7.0 podrá ser alcanzado con una documentación clara y completa de los aspectos pedidos (Descripción del juego con reglas de jugador y servidor, prototipo de interfaces, modelo ER general preliminar y  detalle de Clases principales), con reglas que detallen más que lo mínimo especificado en el enunciado, y con recursos visuales apropiados para presentar la información (documento ordenado, jerarquizado y navegable y un mockup descriptivo). 

Para las entregas posteriores, los criterios para obtener las notas de la escala podrán ser conversados en términos concretos con su ayudante de seguimiento, ya que seguirán criterios generales, pero se adaptarán a las particularidades de cada proyecto.

Revisaré lo de las etiquetas.

Espero que con esto quede más claro, avísame si no por favor.

EDIT: Fue clarificado en el Readme cómo sugerir etiquetas. Esto es en el título de la issue, de la forma "[ETIQUETA] Título", para que luego un/a ayudante o el profesor la confirme.
