### ISSUE TITLE
Probar archivos Tarea 2

### ISSUE THREAD

**Issue by dtgazmuri** [PUCIIC2513/2020-2#10]
Hola

¿Dónde podemos correr o probar los archivos HTML y CSS de la tarea 2 que vayamos creando?

Gracias de antemano

**Comment by JorgeBdelaT** [comment]
Hola! Para probar sus archivos html y css los pueden abrir directamente con el navegador. Sin embargo, existen algunas herramientas que les permiten generar un servidor web y asi poder revisarlo mas facilmente. En este sentido, les recomiendo usar live-server, lo pueden instalar via npm o tambien como [extensión](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) de VS Code, lo que facilita bastante el desarrollo. 

Igualmente el fin de semana subiremos una capsula explicando más en detalle con un ejemplo. Además se les mostrará como emular un servidor desde el cual puedan obtener data usando json-server.

**Comment by dtgazmuri** [comment]
Perfecto, gracias!
