### ISSUE TITLE
T2 | Acerca de - Nosotros

### ISSUE THREAD

**Issue by VicenteMerino** [PUCIIC2513/2020-2#11]
Hola, el acerca de y nosotros pueden estar en una misma vista? Es que no se especifica qué es el acerca de, pero supongo que se refiere a hablar de qué se trata la página y estas dos cosas suelen ir en la misma vista en las páginas web.

**Comment by lldavico** [comment]
Hola!

Si lo deciden así está bien, no hay problema mientras tengan coherencia en su diseño.

Saludos
