### ISSUE TITLE
Uso de JavaScript

### ISSUE THREAD

**Issue by Jprampad** [PUCIIC2513/2020-2#13]
Hola!

Puedo usar js para esta entrega? Aunque no sea lo principal para evaluar, puede facilitar harto la pega.

Saludos!

**Comment by B-Dominguez** [comment]
Hola, sí se puede, mientras se mantengan las buenas prácticas mínimas. Eso sí, como mencionas, no es lo principal a evaluar, por lo que en términos de notas se pedirán todos los esperables de htmo y css (y se recomienda partir dejando eso bueno y asegurado primero)

Éxito!

**Comment by Jprampad** [comment]
Gracias!
