### ISSUE TITLE
Archivo index.html

### ISSUE THREAD

**Issue by bmorrisc** [PUCIIC2513/2020-2#14]
Hola,

Cuando en el enunciado dice que hay que incluir _"Un archivo index.html como punto de entrada"_ se refiere a la landing page o es una vista aparte con links a todas las vistas?

Saludos.

**Comment by nbnavarro** [comment]
Hola @bmorrisc!

No es necesario una vista aparte. Idealmente, desde la landing page se debería poder llegar al resto de vistas.

Mucho ánimo con la entrega! 😄

**Comment by bmorrisc** [comment]
Perfecto, muchas gracias!
