### ISSUE TITLE
Duda cápsula sequelize

### ISSUE THREAD

**Issue by crow-rojas** [PUCIIC2513/2020-2#17]
Hola!

Tenía una duda respecto a la última cápsula de Node. En la primera se mencionó que era mala práctica usar npm y yarn simultáneamente, ya que se podrían generar conflictos entre los archivos, pero, en la cuarta cápsula de sequelize se usa npm y yarn a la vez. Es normal esto? O se puede hacer solo con npm o solo con yarn?

Gracias de antemano!

**Comment by camichavez** [comment]
Hola! Perdón lo tarde
Efectivamente si se puede hacer solo con yarn o solo con npm. Añadí [aquí](https://github.com/PUCIIC2513/2020-2/wiki/Node-App-%7C-%5B4%5D-Datos:-migraciones,-modelos-y-semillas-con-Sequelize) los comandos necesarios para instalar sequelize con yarn. Además, si ocupan yarn cambien su archivo .gitignore para que no se suba el package-lock.json y si se suna el yarn.lock. Espero les sirva!
