### ISSUE TITLE
Logout Token

### ISSUE THREAD

**Issue by Tngarrido** [PUCIIC2513/2020-2#21]
Hola, en la capsula 7 sobre token ocupan postman para agregar el token de un usuario conectado, pero me gustaría saber como puedo enviar esa información desde el lado cliente, he intentado varias cosas, sin embargo aún no puedo hacer el logout de manera efectiva dado que para esta acción me pide el token del usuario, he intentado enviar la información lo más parecido a postman:
![image](https://user-images.githubusercontent.com/42189869/99470800-1ef70a00-2924-11eb-8e10-9130a9508af8.png)
Pero sigo sin resultados, Saludos!

**Comment by B-Dominguez** [comment]
Hola, como cerraste la issue, veo que al parecer lo solucionaste. En general, es bueno incluir la función completa en la imagen (no se ve cómo se pasa segundo parámetro). También, es bueno incluir la información de debuggeo (cómo se sabe que no funciona). Así, se pueden dar mejores respuestas y más rápidas.

Esto podría haber estado fallando por distintos motivos. De lo que se aprecia en la imagen, es irregular el uso de 'Headers' en vez de 'headers' , pero fetch debería convertirlo en minúsculas. También, está el uso de const en vez de var para myHeader.
