### ISSUE TITLE
ReMatch

### ISSUE THREAD

**Issue by danustilovsky** [PUCIIC2513/2020-2#22]
Hola, existe la posibilidad que manden una version actualizada de los resultados de las consultas? Que me aparecen los indices de las posiciones corridas en la gran mayoria de los casos por 1, y al parecer podrian haber cambiado la pagina en wikipedia.

Muchas gracias!

**Comment by B-Dominguez** [comment]
Hola Dan,

Lo comenté hoy para el equipo desarrollador, pero no creo que se alcance a actualizar a buena hora, dado que estamos encima de la entrega. De todas formas, puedes probar haciendo las consultas sobre el texto de ejemplo, almacenándolo en la variable correspondiente, y así podrás saber si tu problema es por un cambio en el contenido de la página (que no sería problema en tu entrega) o algún detalle en tu consulta.

Saludos!

**Comment by danustilovsky** [comment]
Daleee, muchas gracias!

**Comment by valeeeriquelme** [comment]
@danustilovsky te funcionó haciendo eso? Estoy teniendo el mismo problema 😬

**Comment by valeeeriquelme** [comment]
Hola, hice lo de consultar al texto que estaba en el enunciado (almacenarlo en una variable y trabajar con él) y tampoco me calzaba con la posiciones que aparecían como solución, por lo que revisé cual era el trozo de texto al que hacía referencia el resultado esperado y tampoco me hace sentido. 

Se que es un poco tarde para mencionarlo, pero quería dejar esta constancia para que se tenga en consideración al momento de revisar. 

Muchas gracias
![image](https://user-images.githubusercontent.com/37518300/102529197-54eff100-407e-11eb-8e1d-6da0bcad7c33.png)
