### ISSUE TITLE
[Tarea 1] Ítem 2

### ISSUE THREAD

**Issue by VicenteMerino** [PUCIIC2513/2020-2#3]
Hola, el ítem 2 de la tarea dice "2. Las características del juego (que debe contener los aspectos mínimos según
el tipo de juego)" No entendemos muy bien a qué se refiere esto? Se refiere a las reglas que tiene cada tipo de juego, más algunas adicionales que deseemos poner (básicamente un copypaste del Enunciado de tipos de juegos), o a qué se refiere?

**Comment by lldavico** [comment]
Hola! 

Respecto al punto 2. del enunciado, deben **describir en detalle** los elementos que estén presentes en su aplicación web (juego) y cómo interactuarán entre sí durante el transcurso de este. 

Por ejemplo, si eligen el primer tipo de juego, deberán indicar cómo se llamará este, el nombre y características de los territorios que se pueden enfrentar, los tipos y cantidades de recursos que cada territorio posee. También pueden indicar los nombres y tipos de unidades que posee cada territorio y los atributos de combate que tiene cada una de estas unidades, entre otros elementos.

Estas descripciones quedan a **criterio de cada grupo** pudiendo poner en práctica toda su creatividad, sin embargo, deben cumplir con los elementos mínimos del tipo de juego que hayan elegido y que están listadas en el enunciado de [Reglas generales](https://github.com/PUCIIC2513/2020-2/blob/master/Enunciados/Reglas%20Generales.pdf). Por ejemplo, si se debe permitir 2 a 5 jugadores (todos humanos) en el juego, no pueden crear un juego que sea en primera persona versus un computador que realice jugadas automáticamente.

Espero haber resuelto tu duda!

**Comment by vicentevegaulloa** [comment]
Hola!

A partir de lo que dices, no me queda claro cual es la diferencia entre el punto 2 y 3. El enunciado dice:

>  2. Las características del juego (que debe contener los aspectos mínimos según
> el tipo de juego)
> 3. Las reglas detalladas del juego a nivel de usuario

Por lo tanto, si ya detallo los elementos que el usuario verá en el juego en el punto 3, es necesario que también lo haga en el punto 2?
