### ISSUE TITLE
[Tarea 1] Duda lógica del servidor - entrega de jugadas por turnos

### ISSUE THREAD

**Issue by VicenteMerino** [PUCIIC2513/2020-2#4]
![image](https://user-images.githubusercontent.com/47841749/90991496-8d236f00-e577-11ea-9db8-436f6b50954a.png)

Hola, tengo una duda sobre la lógica del juego,. Las reglas generales dicen que "El servidor recibe, hasta una cierta fecha límite, por turno, todas las jugadas de todos los jugadores inscritos" Sin embargo esto es un poco raro, porque si por ejemplo si yo decido atacar a alguien con alguna pieza, y alguien a mi me ataca y el servidor, de alguna forma decide que a mi me atacaron primero y ya no tengo las piezas con las que iba a atacar, de cierta forma "pierdo" esa jugada, ya que no puedo decidir en base a las jugadas de los otros jugadores y si realizan una jugada que "anula" mi jugada no puedo rehacerlo y pierdo el turno, lo cual me parece muy raro. No se si estoy entendiendo mal el enunciado o esto es así y debemos ver que hacer en estas situaciones.

**Comment by B-Dominguez** [comment]
Hola Vicente, 
El lunes comentamos la issue con el equipo docente y ayer martes el profesor decidió dedicar tiempo en la clase para ahondar en explicar la modalidad de los juegos. De todas formas, por si no pudiste verla, te cuento que, si bien es cierto que para la mayoría de los juegos modernos el sistema de turnos puede parecer raro, es un sistema validado del cuál existen múltiples juegos reales. En el enunciado puedes encontrar enlaces de ejemplos de ellos. También, puedes buscar más información de la modalidad, que se llama "Play by (e)Mail" (PBM) (PBeM). Te dejo el enlace a la descripción de Wikipedia y a un ejemplo que el profesor mostró.

Saludos!

https://en.wikipedia.org/wiki/Play-by-mail_game
http://www.warbarons.com/
