### ISSUE TITLE
Duda Indicaciones Enunciado Tarea 1

### ISSUE THREAD

**Issue by vicentevegaulloa** [PUCIIC2513/2020-2#5]
Hola!

No nos queda claro cual es la diferencia entre el punto 2 y 3 de las indicaciones. El enunciado dice:

>  2. Las características del juego (que debe contener los aspectos mínimos según
> el tipo de juego)
> 3. Las reglas detalladas del juego a nivel de usuario

Por lo tanto, si ya detallo los elementos que el usuario verá en el juego en el punto 3, es necesario que también lo haga en el punto 2?

**Comment by lldavico** [comment]
Hola Vicente!

Disculpa la demora en contestar. Los elementos que el usuario verá en el juego, tales como el tablero, los personajes presentes, el color del tablero, etc son parte de las **características del juego**, es decir, **el punto 2**. 

En el **punto 3** deberán indicar, como dice el enunciado, las reglas del juego a nivel de usuario, por lo que no es necesario que en ese punto describan cómo será físicamente lo que verá el usuario en la interfaz, sino los alcances y márgenes en los que este puede actuar.

Ojalá te haya quedado más claro!

Saludos

**Comment by vicentevegaulloa** [comment]
Muchas gracias!
