### ISSUE TITLE
Ítem 10 entega 1

### ISSUE THREAD

**Issue by bmorrisc** [PUCIIC2513/2020-2#7]
Hola!

No me queda muy claro a qué se refiere este punto del enunciado...  tiene relación con los elementos que permiten la interacción del usuario y la página? En ese caso, debería ir acompañando los diseños de la landing page y otras páginas?

**Comment by B-Dominguez** [comment]
Hola! El punto 10 se refiere a elementos que deben estar contenidos transversalmente en las vistas que diseñen, no a una vista en sí misma.

Espero que con eso quede claro.

PD: en general es bueno citar el enunciado o documento al que hagas referencia, para que se te pueda contestar más rápido

**Comment by bmorrisc** [comment]
Perfecto, muchas gracias!
