### ISSUE TITLE
[Tarea 1] Duda Ítem 12 

### ISSUE THREAD

**Issue by javi-saavedra** [PUCIIC2513/2020-2#8]
Holaa! 

Tengo una duda con el enunciado de la Tarea 1. A qué se refiere el punto 12) cuando dice "Diseño Orientado a Objetos de las piezas del juego"? Qué se espera que entreguemos? 🐱

Saludos!

**Comment by nbnavarro** [comment]
Hola @javi-saavedra!

Idealmente, se espera que entreguen un diagrama de clases. 

Mucho ánimo en la tarea! 😄

**Comment by javi-saavedra** [comment]
Muchas Gracias! 💛   @nbnavarro
