### ISSUE TITLE
Duda item 11 y 12

### ISSUE THREAD

**Issue by danustilovsky** [PUCIIC2513/2020-2#9]
Hola, 

No me queda muy claro cual es la diferencia entre los puntos 11 y 12 del enunciado. Claro que los diagramas son diferentes, pero se espera que el diagrama de clases incluya metodos a ser utilizados o simplemente los atributos? Porque en el segundo caso tendria practicamente la misma informacion que el modelo de datos.

Gracias!

**Comment by B-Dominguez** [comment]
Hola, lamentablemente por la hora no se alcanzó a contestar antes de la entrega, pero sí se esperaba que incluyera algunos métodos (los principales que pudietan prever), y herencia, composición u agregación si aplicaba.

**Comment by danustilovsky** [comment]
Hola, @B-Dominguez creo que estas confundido. La entrega segun el enunciado es el 2 de septiembre, osea mañana o no?

**Comment by B-Dominguez** [comment]
Lo siento mucho, espero no te hayas alcanzado a preocupar, pero efectivamente me traspapelé: la entrega es hasta mañana a las 20:00hrs

**Comment by danustilovsky** [comment]
jajajaja solo un poco. Gracias por la respuesta!
